# Generated by Django 3.2.6 on 2021-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=200)),
                ('codeName', models.CharField(max_length=20)),
                ('serviceNumber', models.IntegerField(max_length=20)),
                ('station', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
