# Generated by Django 3.2.6 on 2021-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_measurement_servicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='distance',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
